In [5]:
import tensorflow as tf
from utils import plot_series, load_data_preprocessing


In [7]:
series = load_data_preprocessing('KTG')['harga']

In [10]:
dataset = tf.data.Dataset.from_tensor_slices(series)

# Preview the result
for val in dataset:
   print(val.numpy())

9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
8500.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
8000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0
9000.0

In [11]:

# Window the data
dataset = dataset.window(size=5, shift=1)

# Print the result
for window_dataset in dataset:
  print(window_dataset)

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>
<_VariantDataset element_spe

In [12]:
# Print the result
for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

2023-11-27 14:45:48.314114: W tensorflow/core/framework/dataset.cc:959] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2023-11-27 14:45:48.365439: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:48.420981: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:48.432822: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 8500.0]
[9000.0, 9000.0, 9000.0, 8500.0, 8000.0]
[9000.0, 9000.0, 8500.0, 8000.0, 8000.0]
[9000.0, 8500.0, 8000.0, 8000.0, 8000.0]
[8500.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0,

2023-11-27 14:45:48.959127: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:48.968292: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:48.975510: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:48.982744: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.124530: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.148235: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:45:49.175849: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.182074: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.189281: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.331965: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.336232: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.346984: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.364745: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:45:49.378625: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.388345: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.403178: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.408462: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.419991: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.427266: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.434136: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.439278: W tensorflow/core/data/root_dataset.cc:34

[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:45:49.598808: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.616441: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.645839: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.650678: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:49.658306: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 10000.0]
[9000.0, 9000.0, 9000.0, 10000.0, 10000.0]
[9000.0, 9000.0, 10000.0, 10000.0, 10000.0]
[9000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 

2023-11-27 14:45:49.997260: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.021861: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.042543: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:45:50.327295: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.401746: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.420611: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.430370: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.436876: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 9500.0]
[10000.0, 10000.0, 10000.0, 9500.0, 9500.0]
[10000.0, 10000.0, 9500.0, 9500.0, 9500.0]
[10000.0, 9500.0, 9500.0, 9500.0, 10000.0]
[9500.0, 9500.0, 9500.0, 10000.0, 10000.0]
[9500.0, 9500.0, 10000.0, 10000.0, 10000.0]
[9500.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10

2023-11-27 14:45:50.579939: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.594127: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.599161: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.604742: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.630009: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.658181: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.712130: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.

2023-11-27 14:45:50.796200: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.803163: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:50.809582: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[11000.0, 11000.0, 11000.0, 11000.0, 10500.0]
[11000.0, 11000.0, 11000.0, 10500.0, 10000.0]
[11000.0, 11000.0, 10500.0, 10000.0, 10000.0]
[11000.0, 10500.0, 10000.0, 10000.0, 10000.0]
[10500.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.

2023-11-27 14:45:51.016542: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.022326: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.058251: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 12000.0]
[10000.0, 10000.0, 10000.0, 12000.0, 12000.0]
[10000.0, 10000.0, 12000.0, 12000.0, 12000.0]
[10000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.

2023-11-27 14:45:51.404479: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.411159: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.418536: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.432117: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.443399: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.604438: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.

2023-11-27 14:45:51.626992: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.630174: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.635516: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.659544: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.679141: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.816668: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]


2023-11-27 14:45:51.828562: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.855743: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:51.928683: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.0, 12000.0]
[12000.0, 12000.0, 12000.0, 12000.

2023-11-27 14:45:52.249975: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:52.265037: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:52.280458: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:45:52.374182: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


In [14]:
dataset = tf.data.Dataset.from_tensor_slices(series)

# Window the data but only take those with the specified size
dataset = dataset.window(size=5, shift=1, drop_remainder=True)

# Print the result
for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

2023-11-27 14:46:42.335123: W tensorflow/core/framework/dataset.cc:959] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2023-11-27 14:46:42.338437: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.357365: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.373639: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.508241: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.542558: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 8500.0]
[9000.0, 9000.0, 9000.0, 8500.0, 8000.0]
[9000.0, 9000.0, 8500.0, 8000.0, 8000.0]
[9000.0, 8500.0, 8000.0, 8000.0, 8000.0]
[8500.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0,

2023-11-27 14:46:42.562104: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.576864: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.610216: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:46:42.776464: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.783187: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.787774: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.796734: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.892288: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:42.972719: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:46:42.979551: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:43.175078: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:43.179719: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 8000.0]
[10000.0, 10000.0, 10000.0, 8000.0, 8000.0]
[10000.0, 10000.0, 8000.0, 8000.0, 8000.0]
[10000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0,

2023-11-27 14:46:43.190522: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:43.199755: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:43.210935: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:43.245132: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8000.0]
[8000.0, 8000.0, 8000.0, 8000.0, 8500.0]
[8000.0, 8000.0, 8000.0, 8500.0, 9000.0]
[8000.0, 8000.0, 8500.0, 9000.0, 9000.0]
[8000.0, 8500.0, 9000.0, 9000.0, 9500.0]
[8500.0, 9000.0, 9000.0, 9500.0, 9500.0]
[9000.0, 9000.0, 9500.0, 9500.0, 9000.0]
[9000.0, 9500.0, 9500.0, 9000.0, 9000.0]
[9500.0, 9500.0, 9000.0, 9000.0, 9000.0]
[9500.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0, 9000.0, 9000.0, 9000.0]
[9000.0, 9000.0,

2023-11-27 14:46:44.010375: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.027918: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.047602: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.051602: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.062387: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.077067: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.093883: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.112104: W tensorflow/core/data/root_dataset.cc:34

[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.

2023-11-27 14:46:44.413237: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.450014: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.461077: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.0, 10000.0]
[10000.0, 10000.0, 10000.0, 10000.

2023-11-27 14:46:44.641110: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.663459: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.

2023-11-27 14:46:44.859672: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:44.879980: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 10500.0]
[11000.0, 11000.0, 11000.0, 10500.0, 10000.0]
[11000.0, 11000.0, 10500.0, 10000.0, 10000.0]
[11000.0, 10500.0, 10000.0, 10000.

2023-11-27 14:46:46.317282: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.0, 14000.0]
[14000.0, 14000.0, 14000.0, 14000.

2023-11-27 14:46:46.729808: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.0, 11000.0]
[11000.0, 11000.0, 11000.0, 11000.

2023-11-27 14:46:46.955474: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled
2023-11-27 14:46:47.078530: W tensorflow/core/data/root_dataset.cc:342] Optimization loop failed: CANCELLED: Operation was cancelled


In [15]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.from_tensor_slices(series)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
dataset = dataset.flat_map(lambda window: window.batch(5))

# Print the results
for window in dataset:
  print(window.numpy())

[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 9000.]
[9000. 9000. 9000. 9000. 8500.]
[9000. 9000. 9000. 8500. 8000.]
[9000. 9000. 8500. 8000. 8000.]
[9000. 8500. 8000. 8000. 8000.]
[8500. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8000. 8000. 8000. 8000.]
[8000. 8

In [16]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.from_tensor_slices(series)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create tuples with features (first four elements of the window) and labels (last element)
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

# Print the results
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
  print()

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  8500.0

x =  [9000. 9000. 9000. 8500.]
y =  8000.0

x =  [9000. 9000. 8500. 8000.]
y =  8000.0

x =  [9000. 8500. 8000. 8000.]
y =  8000.0

x =  [8500. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y

In [17]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.from_tensor_slices(series)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create tuples with features (first four elements of the window) and labels (last element)
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

# Shuffle the windows
dataset = dataset.shuffle(buffer_size=10)

# Print the results
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
  print()

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 8500.]
y =  8000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [9000. 9000. 8500. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8500. 8000. 8000. 8000.]
y =  8000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [9000. 8500. 8000. 8000.]
y =  8000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [9000. 9000. 9000. 9000.]
y =  9000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y =  8000.0

x =  [8000. 8000. 8000. 8000.]
y

In [18]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.from_tensor_slices(series)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create tuples with features (first four elements of the window) and labels (last element)
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

# Shuffle the windows
dataset = dataset.shuffle(buffer_size=10)

# Create batches of windows
dataset = dataset.batch(2).prefetch(1)

# Print the results
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())
  print()


x =  [[9000. 9000. 9000. 9000.]
 [9000. 9000. 9000. 9000.]]
y =  [9000. 9000.]

x =  [[9000. 9000. 9000. 9000.]
 [9000. 9000. 9000. 9000.]]
y =  [9000. 9000.]

x =  [[9000. 9000. 9000. 9000.]
 [9000. 9000. 9000. 9000.]]
y =  [9000. 9000.]

x =  [[9000. 9000. 9000. 9000.]
 [9000. 9000. 9000. 9000.]]
y =  [9000. 8500.]

x =  [[8500. 8000. 8000. 8000.]
 [9000. 9000. 9000. 9000.]]
y =  [8000. 9000.]

x =  [[9000. 9000. 8500. 8000.]
 [8000. 8000. 8000. 8000.]]
y =  [8000. 8000.]

x =  [[9000. 8500. 8000. 8000.]
 [8000. 8000. 8000. 8000.]]
y =  [8000. 8000.]

x =  [[9000. 9000. 9000. 9000.]
 [9000. 9000. 9000. 9000.]]
y =  [9000. 9000.]

x =  [[8000. 8000. 8000. 8000.]
 [8000. 8000. 8000. 8000.]]
y =  [8000. 8000.]

x =  [[9000. 9000. 9000. 9000.]
 [8000. 8000. 8000. 8000.]]
y =  [9000. 8000.]

x =  [[8000. 8000. 8000. 8000.]
 [8000. 8000. 8000. 8000.]]
y =  [8000. 8000.]

x =  [[8000. 8000. 8000. 8000.]
 [8000. 8000. 8000. 8000.]]
y =  [8000. 8000.]

x =  [[8000. 8000. 8000. 8000.]
 [8000. 